name: Test the module

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
    - uses: actions/checkout@v6
    - uses: hashicorp/setup-terraform@v3
    - run: ./test.sh
